apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:H4ivDGdgfguy1pkrV5bPm0dB3RK6f7vSjQ2tm9/23/FDu6mwfw==,iv:kXwOYZ6WtUD578k/xxAXcuaZO/Ton0OPX6V2Sva0uvQ=,tag:n5lBmBfoxyjhq6mJzYknsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-25T19:19:22Z'
    mac: ENC[AES256_GCM,data:3P+WUzOpxt0Icg7tH6lQ2bEvbSO0Et788QBg/sbqIvAlI0Ua4wJ2C+vm8ixI3qDNKMF08yiM02iVVtEcPwT32zvkVPdCNbSv2HZsdYYiFruDbL3dYeAZBQSeCEY5whvl+rDrdnLBLoJdiZ7ZAp24HCFpbEBUyycRug6QgA7OQSk=,iv:5PudPMHxzGz0M2wbYDz8NUXrPb3lE58XxPEN4aeCQXg=,tag:3FbmSN7UIy+qpnWwXC0s6w==,type:str]
    pgp:
    -   created_at: '2021-01-25T19:19:21Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA5IcSIMm1rGgAQf/SqCP0zm8kC00F+p2CI74GkysUymzNFqqyMT09Qm7EP2v
            Ch3OgLMH5GfzP8NvFKveH8S4tDxRWp/jNkn6mlwZYt2ol4Oh8H+/aLCRiD9biglz
            Ij5M2Fy9HAhr3Or32ygTeAdsqXgclPraGEJ8EWYSdftCvjoiirXT8U6nDrkagNdH
            c6AVHlrCBbyahCdqcn3TR+CsbyfWSMVHnL38wG5Hz8u4zzGL96oyTXDp50Xkr2Ju
            sFGtrkWgCihst7x8AS/1NVxib4+ewurDdtLKW3YEHfPHmPW421Tx/Xy3ANXWH1vs
            bxu5TXI52wbZbA/4ykPCb2UhbX6Ack8m0rAMjbLSuNJeAbNGtJhOTouVuemlVPa8
            wYnYFOYDkJkBoAgaDi4bmTYhOl1XL2Rc3HFRyDid4/YD2iYo1ALA2z5gKjQMWbJj
            mN1i+sEhoSiy+5IlHZ5dBIMS9WPGICHCU45Y5Nchkw==
            =aU72
            -----END PGP MESSAGE-----
        fp: B89A9DF4693C140E4C4CC959AF47F8E9EE0C1343
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
