apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.10.2
        args:
        - --source=service
        - --source=ingress
        #- --domain-filter=larshaugan.net # (optional) limit to only example.com domains; change to match the zone created above.
        #- --zone-id-filter= # (optional) limit to a specific zone.
        - --provider=cloudflare
        - --log-level=debug
          #- --cloudflare-proxied # (optional) enable the proxy feature of Cloudflare (DDOS protection, CDN...)
        envFrom:
        - secretRef:
            name: cloudflare-api-token-secret
