apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns

namespace: external-dns

resources:
- namespace.yaml
- cf-secret.yaml
- deployment.yaml
- sa.yaml
- role.yaml
- rolebinding.yaml
